# Autogenerated wrapper script for raxml_ng_jll for x86_64-linux-gnu
export raxml_ng

JLLWrappers.@generate_wrapper_header("raxml_ng")
JLLWrappers.@declare_executable_product(raxml_ng)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        raxml_ng,
        "bin/raxml-ng",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
